name: slugfield
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Svintsov Dmitry <sacrud@uralbash.ru>
homepage: https://github.com/ITCase/slugfield/

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  slugify: '>=0.1.1'
  browser: '>=0.10.0 <0.11.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter
