name: slugfield
description: Generate a slug for connected inputs.
version: 0.0.2
author: Svintsov Dmitry <sacrud@uralbash.ru>
homepage: https://github.com/ITCase/slugfield/

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  slugify: '>=0.1.1 <0.3.0'
  browser: '>=0.10.0 <0.11.0'

dev_dependencies:
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter
